[build-system]
requires = ["setuptools>=80.9"]
build-backend = "setuptools.build_meta"

[project]
name = "django_common_utils"
version = "0.1"
readme = "README.txt"
requires-python = ">= 3.12"

[tool.setuptools]
py-modules = ["captcha_disable_decorator", "django_common_utils"]